too dumb to squash, sry
Bios-Marcel/baka pull request #23
Opened 2024-08-08 21:39 UTC by bugabinga

2024-08-10 10:34 UTC, Bios-Marcel requested changes

2024-08-10 10:34 UTC, Bios-Marcel commented on src/main/java/link/biosmarcel/baka/Main.java
> +				if( os.indexOf("nux") >= 0) {
Probs not on purpose?

2024-10-31 10:00 UTC, Bios-Marcel commented
No squashy xD

2024-10-31 12:55 UTC, bugabinga commented
commits will be fixed in new PR

2024-10-31 12:55 UTC, closed without merging